### ISSUE TITLE
Help displays wrong info for "'-G <byte count>': Get Random"

### ISSUE THREAD

**Issue by zveriu** [Infineon/eltt2#11]
################################################################################

Current:

pi@raspberrypi:~/eltt2 $ ./eltt2 -h | grep -i random
'-G <byte count>': Get Random
        -> Enter desired number of random bytes in hex like '32' for 0x32

pi@raspberrypi:~/eltt2 $ ./eltt2 -G 32

Bad option. Enter a hex value between 0x01 and 0x20.
Unexpected error: 0xFFFFFFFE

################################################################################

Expected:

pi@raspberrypi:~/eltt2 $ ./eltt2 -h | grep -i random
'-G <byte count>': Get Random
        -> Enter desired number of random bytes in hex like '20' (no 0x prefix) for 32 bytes

################################################################################

Environment:

pi@raspberrypi:~/eltt2 $ git show --name-only
commit db61889621aa575332c793ea9ed23c6cb6281d99
Author: Peter Huewe <peterhuewe@gmx.de>
Date:   Thu Mar 22 23:33:27 2018 +0100

    Fix whitespace/indention to make code more readable
    
    For some reason the indention and whitespaces were quite messed up.
    This patchset fixes this and makes the code much more readable
    
    Signed-off-by: Peter Huewe <peterhuewe@gmx.de>

eltt2.c
eltt2.h

**Comment by PeterHuewe** [comment]
@zveriu I would close this if you accept.

**Comment by zveriu** [comment]
Thanks for the quick fix :)! Closing as it the help is inline with the functionality, no user confusion anymore :).
