### ISSUE TITLE
The -g parameter does not show the TPM_PT_PERMANENT flags status? 

### ISSUE THREAD

**Issue by nickko88** [Infineon/eltt2#15]
When use ./eltt2 -g The follow parameters are not shown.
ownerAuthSet
endorsementAuthSet
lockoutAuthSet
disableClear
inLockout
tpmGeneratedEPS

**Comment by nickko88** [comment]
I found that If use SLB9670VQ2.0 FW7.62 every flags will shown, but on SLB9670VQ2.0 FW7.85  is not.

**Comment by PeterHuewe** [comment]
Thanks for the report - you are correct.
The reason is that the TPM_PT_PERMANENT flags belong to the PT_VAR group, not PT_FIXED.
So they should not have shown up in `-g` but in `-v`
TPMs with revision 1.16 (e.g. 7.62) did not enforce the group boundary, revision 1.38 do (e.g. 7.85).
I will create a fix for this

**Comment by PeterHuewe** [comment]
Closed via #16

**Comment by nickko88** [comment]
Hi Peter,

Thanks a lot.

Sincerely,
注意事項: TPM所有相關資料需從MyICP帳號下載。
若有需求，請告知，我將會指導申請帳號與資料。
Nick
Silicon Application Corp./品佳股份有限公司
Nick.Ko/柯佳均, Senior FAE
E-Mail: nick.ko@sacsys.com.tw<mailto:nick.ko@sacasys.com.tw>
Tel: +886-2-8226-1500#83243
Mobile: +886-963-358-858
________________________________
本人免責聲明如下：本人所提供之一切設計服務,包括但不限於提供任何軟硬體工程上之建議或意見以及電腦程式軟體上之撰寫服務或軟體之程式修改等等均屬例外無償服務之性質,因此對於上該本人所提供之無償服務之內容,收受者應自行判斷抉擇或評估其適用性及正確性並自行承擔後續所有可能衍生之一切責任,本人對上述無償所提供之一切服務一概不負擔任何法律責任.
Notice: Using this software indicates your acceptance of the disclaimer hereunder:
THIS SOFTWARE IS for your reference only and PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. your Using this software/firmware is based on your own discretion, IN NO EVENT SHALL THE COPYRIGHT OWNER OR Provider BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
________________________________
