### ISSUE TITLE
TPM Error 0x00000100: TPM not initialized.

### ISSUE THREAD

**Issue by kent1026** [Infineon/eltt2#7]
send
sudo ./eltt2 -g 
print

TPM capability information of fixed properties:
=========================================================
TPM_PT_FAMILY_INDICATOR:        2.0
TPM_PT_LEVEL:                   0
TPM_PT_REVISION:                116
TPM_PT_DAY_OF_YEAR:             15
TPM_PT_YEAR:                    2016
TPM_PT_MANUFACTURER:            IFX
TPM_PT_VENDOR_STRING:           SLB9670
TPM_PT_VENDOR_TPM_TYPE:         0
TPM_PT_FIRMWARE_VERSION:        7.62.3126.0

TPM_PT_MEMORY:
=========================================================
Shared RAM:                     0 CLEAR
Shared NV:                      1 SET
Object Copied To Ram:           1 SET

TPM_PT_PERMANENT:
=========================================================
Owner Auth Set:                 0 CLEAR
Endorsement Auth Set:          0 CLEAR
Lockout Auth Set:               0 CLEAR
Disable Clear:                  1 SET
In Lockout:                     1 SET
TPM Generated EPS:              0 CLEAR

send
sudo ./eltt2 -t full

print

Successfully tested. Works as expected.

but send
sudo ./eltt2 -u state
or
sudo ./eltt2 -u clear
or 
sudo ./eltt2 -u 

all print

TPM Error 0x00000100: TPM not initialized.

thanks

**Comment by PeterHuewe** [comment]
Hi,
this is expected and correct.
The TPM returns TPM2_RC_INITIALÌZE (0x100)
for every command except TPM2_Startup if there WAS NO TPM2_Startup
for TPM2_Startup if there already WAS  a TPM2_Startup.

Your Bios/UEFI/Firmware usually sends a TPM2_Startup, and if not the Linux Kernel TPM Device Driver sends one.

IF you are using some kind of eval board with a reset button or you can reset the TPM somehow,
you can re-run the command and see that it will succeed.

**Comment by PeterHuewe** [comment]
@kent1026: can we close this?

**Comment by kent1026ng0** [comment]
ok thanks
